import type { LancerActorType } from "./actor/lancer-actor";
import type { LancerItemType } from "./item/lancer-item";
export declare function WELCOME(changelog: string): string;
export declare const LANCER: {
    ASCII: string;
    log_prefix: "LANCER |";
    setting_migration_version: "systemMigrationVersion";
    setting_core_data: "coreDataVersion";
    setting_lcps: "installedLCPs";
    setting_stock_icons: "keepStockIcons";
    setting_welcome: "hideWelcome";
    setting_floating_damage_numbers: "floatingNumbers";
    setting_ui_theme: "uiTheme";
    setting_compcon_login: "compconLogin";
    setting_status_icons: "statusIconConfig";
    setting_automation: "automationOptions";
    setting_automation_switch: "automationSwitch";
    setting_automation_attack: "attackSwitch";
    setting_actionTracker: "actionTracker";
    setting_pilot_oc_heat: "autoOCHeat";
    setting_overkill_heat: "autoOKillHeat";
    setting_auto_structure: "autoCalcStructure";
    setting_dsn_setup: "dsnSetup";
    setting_square_grid_diagonals: "squareGridDiagonals";
    setting_tag_config: "tagConfig";
};
export declare function friendly_entrytype_name(type: LancerItemType | LancerActorType, count?: number): string;
export declare const GENERIC_ITEM_ICON = "systems/lancer/assets/icons/generic_item.svg";
export declare function TypeIcon(type: string, macro?: boolean): string;
export declare function replaceDefaultResource(current: string | null | undefined, ...replacements: Array<string | null>): string;
