name: Publish release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup node
      uses: actions/setup-node@v4
      with:
        node-version: 18

    - name: Install dependencies
      run: yarn

    - name: Extract tag version number
      id: get_version
      uses: battila7/get-version-action@v2

    - name: Run Vite build
      env:
        VERSION: ${{steps.get_version.outputs.version-without-v}}
        GH_PROJECT: ${{github.repository}}
        GH_TAG: ${{github.event.release.tag_name}}
      run: yarn build

    - name: Create zip archive
      working-directory: dist
      run: zip -r ./module.zip module.json style.css style.css.map scripts/ templates/ lang/
    
    - name: Install jq and yq
      run: |
        sudo apt-get update
        sudo apt-get install -y jq
        sudo pip install yq

    - name: Extract release notes from CHANGELOG.md
      id: extract_release_notes
      run: |
        VERSION=${{steps.get_version.outputs.version-without-v}}
        RELEASE_NOTES=$(awk "/^# ${VERSION} - /,/^# /" CHANGELOG.md | sed '$d')
        echo "::set-output name=notes::$RELEASE_NOTES"
        
    - name: Update release with files
      id: create_version_release
      uses: ncipollo/release-action@v1
      with:
        allowUpdates: true
        name: ${{ github.event.release.name }}
        draft: ${{ github.event.release.unpublished }}
        prerelease: ${{ github.event.release.prerelease }}
        token: ${{ secrets.GITHUB_TOKEN }}
        artifacts: "./dist/module.json, ./dist/module.zip"
        tag: ${{ github.event.release.tag_name }}
        body: |
          ${{ steps.extract_release_notes.outputs.notes }}

          [Full Changelog](https://github.com/annoyedb/lancer-alternative-sheets/blob/master/CHANGELOG.md)